export default {
  lastUpdated: '2026-06-25T14:30:00',
  items: [
  {
    id: 'FUE-00001',
    nombre_fuente: 'Lanzamiento del nuevo framework de JavaScript',
    resumen_ia: 'El nuevo framework promete revolucionar la forma en que construimos aplicaciones web, con mejor rendimiento y una DX sin precedentes. Entre las características mas destacadas se incluye un compilador optimizado que genera bundles hasta 60% mas livianos, un sistema de reactividad basado en señales que elimina la necesidad de reconciliaión virtual del DOM, y una arquitectura de renderizado por islas que permite hidratar solo las partes interactivas de la página. Los desarrolladores destacan también el hot module replacement nativo, que conserva el estado de la aplicación durante el desarrollo, y un sistema de errores con sugerencias contextuales en tiempo real. El equipo detrás del proyecto planea lanzar una versión estable a finales de año, con soporte oficial para TypeScript, integración con las principales herramientas de testing y un CLI unificado. La comunidad ya prepara tutoriales, cursos y conferencias para acompañar el lanzamiento, y los primeros benchmarks muestran resultados alentadores tanto en cargas iniciales como en interacciones complejas, posicionándolo como una alternativa seria a los frameworks tradicionales.',
    thumbnail: 'https://picsum.photos/seed/noticia1/600/400',
    link_web: 'https://dev.to/news/javascript-framework-2026',
    link_edit_entry: 'https://ejemplo.com/admin/editar/FUE-00001',
    fecha_publicacion: '2026-06-25',
    fecha_scrapeo: '2026-07-17T03:00:00.000Z',
    tonos_sociales: ['Positivo', 'Neutro'],
    fuente_institucional: 'Dev.to',
    tipo_fuente: 'Sitio web o portal',
    es_oficial: true,
    validado: true,
    analizado: true,
    actores_principales: ['Ana García', 'Carlos Ruiz'],
    notas_de_trabajo: 'Verificar si el framework ya tiene soporte oficial para SSR. Preguntar al equipo de backend si podemos integrarlo en el sprint 14.',
    adjuntos: ['https://archivos.ejemplo.com/informes/informe-lanzamiento-framework.pdf'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [
      { thumb: 'https://picsum.photos/seed/noticia1a/300/200', full: 'https://picsum.photos/seed/noticia1a/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia1b/300/200', full: 'https://picsum.photos/seed/noticia1b/600/400' }
    ],
    has_video: true,
    links_videos: [
      'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      'https://www.youtube.com/watch?v=jNQXAC9IVRw',
      'https://www.youtube.com/watch?v=9bZkp7q19f0'
    ],
    temas: [
      { titulo: 'Rendimiento y optimizacion del tiempo de carga inicial en dispositivos moviles', resumen: 'Los benchmarks muestran una mejora del 40% en el tiempo de carga inicial, con reducciones aun mayores en moviles de gama baja. Las metricas de Core Web Vitals mejoran gracias al compilador optimizado y al renderizado por islas.', tono_social: 'Positivo', fecha_narrativa: '2026-06-24', notas_de_trabajo: 'Preguntar al equipo de frontend si estos benchmarks replican en nuestro stack actual. Medir antes y despues de la migracion.' },
      { titulo: 'Experiencia de desarrollo (DX) para equipos que trabajan de forma remota', resumen: 'La experiencia de desarrollo mejora con hot module replacement nativo que conserva el estado, errores con sugerencias contextuales y una integracion profunda con editores populares. El CLI unificado simplifica la creacion de proyectos y reduce las tareas repetitivas.', tono_social: 'Positivo', fecha_narrativa: '2026-06-25' },
      { titulo: 'Ecosistema de plugins y el rol de la comunidad alrededor del framework', resumen: 'El ecosistema supero los 200 plugins comunitarios activos, desde integraciones con bases de datos y frameworks de testing hasta utilidades de accesibilidad. La comunidad contribuye con documentacion y los mantenedores garantizan compatibilidad con las versiones estables.', tono_social: 'Neutro', fecha_narrativa: null, notas_de_trabajo: 'Verificar si los plugins criticos que usamos ya tienen soporte oficial. Si no, evaluar contribuir o buscar alternativas.' }
    ]
  },
  {
    id: 'FUE-00002',
    nombre_fuente: 'Actualizacion importante de seguridad en navegadores',
    resumen_ia: 'Los principales navegadores liberan parches criticos que afectan a millones de usuarios en todo el mundo.',
    thumbnail: 'https://picsum.photos/seed/noticia2/600/400',
    link_web: 'https://blog.mozilla.org/security-update',
    fecha_publicacion: '2026-06-22',
    fecha_scrapeo: '2026-06-22T09:15:00',
    tonos_sociales: ['Negativo'],
    fuente_institucional: 'Mozilla Blog',
    tipo_fuente: 'Gacetilla o comunicado de prensa',
    es_oficial: false,
    validado: false,
    analizado: true,
    actores_principales: ['Mozilla', 'Google Chrome Team'],
    adjuntos: [],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [],
    has_video: true,
    links_videos: ['https://www.youtube.com/watch?v=kXYiU_JCYtU'],
    temas: [
      { titulo: 'Parche critico de seguridad para la vulnerabilidad CVE-2026-1234 en navegadores', resumen: 'Se parcheo la vulnerabilidad CVE-2026-1234, catalogada como critica, que afectaba a todos los navegadores basados en Chromium y permitia ejecucion remota de codigo. Se recomienda actualizar todas las versiones afectadas: hay explotaciones activas que instalan malware sin que el usuario lo note.', tono_social: 'Negativo', fecha_narrativa: '2026-06-22' }
    ]
  },
  {
    id: 'FUE-00003',
    nombre_fuente: 'La inteligencia artificial llega al desarrollo web',
    resumen_ia: 'Herramientas basadas en IA ahora pueden generar componentes completos a partir de descripciones en lenguaje natural.',
    thumbnail: 'https://picsum.photos/seed/noticia3/600/400',
    link_web: 'https://openai.com/blog/ai-web-development',
    fecha_publicacion: '2026-06-20',
    fecha_scrapeo: '2026-06-20T18:45:00',
    tonos_sociales: ['Positivo', 'Negativo'],
    fuente_institucional: 'OpenAI Blog',
    tipo_fuente: 'Gacetilla o comunicado de prensa',
    es_oficial: true,
    validado: true,
    analizado: true,
    actores_principales: ['OpenAI'],
    notas_de_trabajo: 'Pendiente revisar impacto en usuarios finales. Coordinar con el equipo de QA para priorizar las pruebas de regresion antes del release.',
    adjuntos: ['https://archivos.ejemplo.com/comunicados/comunicado-ia-desarrollo-web.pdf'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [
      { thumb: 'https://picsum.photos/seed/noticia3a/300/200', full: 'https://picsum.photos/seed/noticia3a/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia3b/300/200', full: 'https://picsum.photos/seed/noticia3b/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia3c/300/200', full: 'https://picsum.photos/seed/noticia3c/600/400' }
    ],
    has_video: true,
    links_videos: [
      'https://www.youtube.com/watch?v=hY7m5jjJ5mQ',
      'https://www.youtube.com/watch?v=oHg5SJYRHA0'
    ],
    temas: [
      { titulo: 'Generacion de codigo', resumen: 'El modelo especializado produce componentes completos con JSX, estilos CSS y logica de estado a partir de descripciones en lenguaje natural. Los desarrolladores iteran rapidamente, refinan el resultado y lo exportan al editor, acelerando el prototipado.', tono_social: 'Positivo', fecha_narrativa: '2026-06-19', notas_de_trabajo: 'Probar el generador con un componente real del proyecto para evaluar calidad del output y si es util en nuestro workflow.' },
      { titulo: 'Editor inteligente', resumen: 'El plugin de VS Code integra sugerencias contextuales basadas en el codigo abierto en el editor y en el contexto del proyecto. Ofrece autocompletado avanzado, deteccion de errores de estilo y accesibilidad, y genera codigo desde lenguaje natural sin salir del entorno.', tono_social: 'Positivo', fecha_narrativa: '2026-06-20' },
      { titulo: 'Productividad', resumen: 'Los equipos que adoptaron la generacion asistida reportan hasta tres veces mas rapidez en prototipado y menos horas en interfaces repetitivas. El tiempo ahorrado se destina a revision de calidad, cobertura de pruebas y refinamiento de la experiencia de usuario.', tono_social: 'Positivo', fecha_narrativa: '2026-06-18', notas_de_trabajo: 'Las metricas de productividad suenan prometedoras. Pedir al equipo que registre su experiencia durante dos semanas para comparar.' },
      { titulo: 'Limites', resumen: 'El modelo presenta limitaciones en logica de negocio compleja y en edge cases poco documentados. Las respuestas se vuelven incoherentes con multiples dependencias o reglas de validacion ambiguas, por lo que requiere correccion manual. Se recomienda usarlo como punto de partida.', tono_social: 'Negativo', fecha_narrativa: null }
    ]
  },
  {
    id: 'FUE-00004',
    nombre_fuente: 'Nuevas especificaciones de CSS para 2026',
    resumen_ia: 'El W3C anuncia nuevas capacidades de CSS que simplifican el layout y eliminan la necesidad de frameworks pesados.',
    thumbnail: 'https://picsum.photos/seed/noticia4/600/400',
    link_web: 'https://w3.org/css-2026-specs',
    link_edit_entry: 'https://ejemplo.com/admin/editar/FUE-00004',
    fecha_publicacion: '2026-06-15',
    fecha_scrapeo: '2026-06-15T11:00:00',
    tonos_sociales: ['Positivo'],
    fuente_institucional: 'W3C',
    tipo_fuente: 'Decreto o norma',
    es_oficial: true,
    validado: true,
    analizado: true,
    actores_principales: ['W3C', 'Rachel Andrews', 'Jake Archibald'],
    notas_de_trabajo: 'Evaluar si anchor positioning cubre los casos de dropdowns del proyecto. Si no, mantener la libreria actual como fallback hasta que madure.',
    adjuntos: ['https://archivos.ejemplo.com/specs/spec-css-2026.pdf', 'https://archivos.ejemplo.com/specs/anexo-ejemplos-layout.html'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [
      { thumb: 'https://picsum.photos/seed/noticia4a/300/200', full: 'https://picsum.photos/seed/noticia4a/600/400' }
    ],
    has_video: true,
    links_videos: ['https://www.youtube.com/watch?v=YQHsXMglC9A', 'https://www.instagram.com/reel/DFwJRp9sp1i/','https://www.instagram.com/tv/CD1ra-YgcBe/'],
    temas: [
      { titulo: 'Anchor positioning y el nuevo modelo de posicionamiento relativo al documento', resumen: 'La especificacion de anchor positioning posiciona elementos relativos a otros del documento sin JavaScript. Simplifica tooltips, dropdowns, popovers y menus que antes requerian calculos manuales o librerias externas. Los navegadores modernos ya la soportan nativamente.', tono_social: 'Positivo', fecha_narrativa: '2026-06-14' },
      { titulo: 'Scroll-driven animations y el renderizado progresivo vinculado al desplazamiento de la pagina', resumen: 'Las animaciones vinculadas al desplazamiento se ejecutan nativamente, sincronizadas con la posicion de la pagina en lugar del tiempo. Permiten storytelling, barras de progreso y efectos de parallax sin librerias de terceros ni scroll listeners, con mejor rendimiento.', tono_social: 'Positivo', fecha_narrativa: '2026-06-15', notas_de_trabajo: 'Las scroll-driven animations parecen ideales para la seccion de presentacion del producto. Hacer un proof of concept esta semana.' }
    ]
  },
  {
    id: 'FUE-00005',
    nombre_fuente: 'Node.js 24 entra en LTS',
    resumen_ia: 'La version de soporte a largo plazo trae mejoras significativas en rendimiento y nuevas APIs estables.',
    thumbnail: 'https://picsum.photos/seed/noticia5/600/400',
    link_web: 'https://nodejs.org/blog/node-24-lts',
    fecha_publicacion: '2026-06-10',
    fecha_scrapeo: '2026-06-10T16:30:00',
    tonos_sociales: ['Positivo', 'Neutro'],
    fuente_institucional: 'Node.js Blog',
    tipo_fuente: 'Gacetilla o comunicado de prensa',
    es_oficial: true,
    validado: null,
    analizado: true,
    actores_principales: ['Node.js Foundation'],
    notas_de_trabajo: 'La guia de migracion es bastante clara. Proponer una reunion con el equipo para definir el plan de migracion desde Node 20 antes de que termine el trimestre.',
    adjuntos: ['https://archivos.ejemplo.com/node/notas/node24-lts-release-notes.pdf', 'https://archivos.ejemplo.com/node/benchmarks/benchmarks-memoria.xlsx', 'https://archivos.ejemplo.com/node/guias/guia-migracion-node20-22.pdf'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [
      { thumb: 'https://picsum.photos/seed/noticia5a/300/200', full: 'https://picsum.photos/seed/noticia5a/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia5b/300/200', full: 'https://picsum.photos/seed/noticia5b/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia5c/300/200', full: 'https://picsum.photos/seed/noticia5c/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia5d/300/200', full: 'https://picsum.photos/seed/noticia5d/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia5e/300/200', full: 'https://picsum.photos/seed/noticia5e/600/400' }
    ],
    has_video: true,
    links_videos: [
      'https://www.youtube.com/watch?v=ckZ7mTfj2oE',
      'https://www.youtube.com/watch?v=nfWlot6h_JM',
      'https://www.youtube.com/watch?v=vLx9fBdfF0E'
    ],
    temas: [
      { titulo: 'Nuevas APIs estables de testing nativo y watch mode integrado', resumen: 'La version LTS incorpora una API nativa de testing que elimina dependencias externas para los casos mas comunes, y un watch mode integrado. Tambien se estabilizan APIs de red y streams, manteniendo compatibilidad hacia atras para una adopcion gradual.', tono_social: 'Positivo', fecha_narrativa: '2026-06-10', notas_de_trabajo: 'La API de testing nativa podria reemplazar vitest en algunos proyectos. Hacer una prueba de concepto con un modulo pequeño.' },
      { titulo: 'Rendimiento en memoria y latencia bajo alta concurrencia de peticiones', resumen: 'Las mediciones sobre Express muestran una reduccion del 40% en uso de memoria gracias a la optimizacion del motor V8 y la cache interna. En alta concurrencia, el throughput mejoro con latencia mas estable y menor consumo de CPU.', tono_social: 'Positivo', fecha_narrativa: null, notas_de_trabajo: 'Comparar estos resultados con nuestro servidor actual. Si la mejora es real, justifica la migracion al LTS.' },
      { titulo: 'Migracion gradual desde Node 20 y 22 con la guia oficial de compatibilidad', resumen: 'La guia oficial detalla la migracion desde Node 20 y 22, con APIs deprecadas y alternativas, ejemplos antes y despues, y scripts para detectar usos incompatibles. Incluye una tabla de compatibilidad; la migracion de proyectos medianos toma medio dia.', tono_social: 'Neutro', fecha_narrativa: '2026-06-09' }
    ]
  },
  {
    id: 'FUE-00006',
    nombre_fuente: 'El estado del ecosistema npm en 2026',
    resumen_ia: 'Un analisis completo de las tendencias, paquetes mas descargados y desafios del ecosistema de Node.',
    thumbnail: 'https://picsum.photos/seed/noticia6/600/400',
    link_web: 'https://npmjs.com/state-of-ecosystem-2026',
    fecha_publicacion: '2026-06-05',
    fecha_scrapeo: '2026-06-05T08:20:00',
    tonos_sociales: [],
    fuente_institucional: 'npm Blog',
    tipo_fuente: 'Sitio web o portal',
    es_oficial: false,
    validado: true,
    analizado: true,
    actores_principales: [],
    adjuntos: [],
    screenshot: null,
    imagenes: [],
    has_video: false,
    temas: []
  },
  {
    id: 'FUE-00007',
    nombre_fuente: 'TypeScript 6: lo que necesitas saber',
    resumen_ia: 'La nueva version incluye patron matching, mejor inferencia de tipos y soporte nativo para decorators.',
    thumbnail: 'https://picsum.photos/seed/noticia7/600/400',
    link_web: 'https://typescriptlang.org/blog/ts6',
    link_edit_entry: 'https://ejemplo.com/admin/editar/FUE-00007',
    fecha_publicacion: '2026-05-28',
    fecha_scrapeo: '2026-05-28T22:10:00',
    tonos_sociales: ['Positivo', 'Negativo'],
    fuente_institucional: 'TypeScript Blog',
    tipo_fuente: 'Gacetilla o comunicado de prensa',
    es_oficial: false,
    validado: false,
    analizado: true,
    actores_principales: ['Anders Hejlsberg', 'Microsoft'],
    adjuntos: ['https://archivos.ejemplo.com/typescript/notas-release-ts6.md'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [
      { thumb: 'https://picsum.photos/seed/noticia7a/300/200', full: 'https://picsum.photos/seed/noticia7a/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia7b/300/200', full: 'https://picsum.photos/seed/noticia7b/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia7c/300/200', full: 'https://picsum.photos/seed/noticia7c/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia7d/300/200', full: 'https://picsum.photos/seed/noticia7d/600/400' }
    ],
    has_video: false,
    temas: [
      { titulo: 'Patron matching con exhaustiveness checking y desestructuracion de tipos', resumen: 'La nueva sintaxis match/case ofrece coincidencia de patrones con exhaustiveness checking, que obliga a cubrir todos los casos posibles. Elimina errores por condiciones incompletas y soporta desestructuracion, guardas y rangos, integrándose con el sistema de tipos.', tono_social: 'Positivo', fecha_narrativa: '2026-05-28' },
      { titulo: 'Decorators nativos sin transpiladores adicionales en clases y metodos', resumen: 'El soporte oficial de decorators llega sin transpiladores adicionales, simplificando la configuracion. Funcionan nativamente en clases y metodos, y su integracion con la inferencia de tipos permite abstracciones mas seguras para inyeccion de dependencias y validacion.', tono_social: 'Positivo', fecha_narrativa: '2026-05-27' },
      { titulo: 'Inferencia de tipos mejorada en funciones genericas y uniones complejas', resumen: 'La inferencia de tipos en funciones genericas es mucho mas precisa, en especial con tipos condicionales y mapeo de uniones. El compilador deduce tipos donde antes se requerian anotaciones manuales, mejorando el autocompletado y detectando errores mas temprano.', tono_social: 'Positivo', fecha_narrativa: null },
      { titulo: 'Breaking changes y la migracion planificada hacia TypeScript 7', resumen: 'Aunque mantiene compatibilidad total hacia atras, varias sintaxis deprecadas seran eliminadas en TypeScript 7. Las herramientas de migracion automatizan la transformacion, pero los patrones muy antiguos requieren revision manual, por lo que conviene planificar la actualizacion con anticipacion.', tono_social: 'Negativo', fecha_narrativa: '2026-05-26' }
    ]
  },
  {
    id: 'FUE-00008',
    nombre_fuente: 'WebAssembly fuera del navegador',
    resumen_ia: 'Cada vez mas frameworks adoptan WASM para ejecutar codigo intensivo en el servidor con rendimiento nativo.',
    thumbnail: null,
    link_web: 'https://wasm.org/server-side-2026',
    fecha_publicacion: '2026-05-15',
    fecha_scrapeo: '2026-05-15T13:45:00',
    tonos_sociales: ['Positivo', 'Neutro'],
    fuente_institucional: 'WebAssembly',
    tipo_fuente: 'Sitio web o portal',
    es_oficial: true,
    validado: true,
    analizado: true,
    actores_principales: [],
    notas_de_trabajo: 'Comparar con Alternativas. Pedir a los desarrolladores que hagan un benchmark con el runtime actual y evaluamos si vale la pena migrar en Q3.',
    adjuntos: ['https://archivos.ejemplo.com/wasm/wasm-server-benchmarks.pdf', 'https://archivos.ejemplo.com/wasm/runtime-comparativa.xlsx'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [
      { thumb: 'https://picsum.photos/seed/noticia8a/300/200', full: 'https://picsum.photos/seed/noticia8a/600/400' }
    ],
    has_video: false,
    temas: [
      { titulo: 'WASM runtime optimizado para funciones serverless de borde', resumen: 'Los nuevos runtimes optimizados para serverless ejecutan modulos WebAssembly con arranque minimo y bajo consumo de recursos. Compilar codigo intensivo a WASM y desplegarlo en funciones de borde acerca el procesamiento al usuario, con overhead cada vez menor.', tono_social: 'Positivo', fecha_narrativa: '2026-05-15', notas_de_trabajo: 'Evaluar si el runtime de borde es compatible con nuestro proveedor de hosting actual. Verificar limitaciones de memoria.' },
      { titulo: 'Casos de uso frecuentes de WebAssembly fuera del navegador', resumen: 'Los usos mas frecuentes del WASM fuera del navegador incluyen procesamiento de imagenes y video, parseo de PDFs y hojas de calculo, y computacion cientifica intensiva. Se benefician de la velocidad nativa y del aislamiento de memoria, reduciendo costos.', tono_social: 'Neutro', fecha_narrativa: null }
    ]
  },
  {
    id: 'FUE-00009',
    nombre_fuente: 'Tendencias de UX para aplicaciones web',
    resumen_ia: 'Micro-interacciones, modo oscuro adaptativo y navegacion gestual definen el panorama de diseño actual.',
    thumbnail: 'https://picsum.photos/seed/noticia9/600/400',
    link_web: 'https://nngroup.com/ux-trends-2026',
    fecha_publicacion: '2026-04-30',
    fecha_scrapeo: '2026-04-30T07:30:00',
    tonos_sociales: ['Positivo', 'Neutro'],
    fuente_institucional: 'Nielsen Norman Group',
    tipo_fuente: 'Libro o publicación',
    es_oficial: false,
    validado: null,
    analizado: true,
    actores_principales: ['María López', 'Google UX', 'Nielsen Norman Group'],
    adjuntos: ['https://archivos.ejemplo.com/ux/ux-trends-2026-reporte.pdf'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [
      { thumb: 'https://picsum.photos/seed/noticia9a/300/200', full: 'https://picsum.photos/seed/noticia9a/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia9b/300/200', full: 'https://picsum.photos/seed/noticia9b/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia9c/300/200', full: 'https://picsum.photos/seed/noticia9c/600/400' }
    ],
    has_video: false,
    temas: [
      { titulo: 'Micro-interacciones', resumen: 'Las micro-interacciones bien disenadas mejoran la percepcion de respuesta y guian al usuario. Hover con feedback tactil, transiciones entre estados de carga y confirmaciones animadas reducen la espera percibida y aumentan la confianza en el sistema.', tono_social: 'Positivo', fecha_narrativa: '2026-04-30' },
      { titulo: 'Modo oscuro adaptativo segun la hora del dia y las preferencias del sistema operativo', resumen: 'La adaptacion automatica del tema considera la hora del dia y las preferencias del sistema operativo. El modo oscuro ajusta contraste, brillo y sombras para mantener legibilidad y reducir la fatiga visual, respetando la preferencia del usuario sin recargar la aplicacion.', tono_social: 'Neutro', fecha_narrativa: null },
      { titulo: 'Navegacion gestual con swipes y arrastres en apps web progresivas', resumen: 'Las apps web progresivas incorporan gestos nativos como swipes y arrastres para navegar y desplegar paneles. Estos patrones moviles llegan al navegador gracias a las APIs de puntero y tactil, ofreciendo una experiencia mas fluida en dispositivos tactiles.', tono_social: 'Positivo', fecha_narrativa: '2026-04-29' }
    ]
  },
  {
    id: 'FUE-00010',
    nombre_fuente: 'Guia completa de testing en el frontend',
    resumen_ia: 'Desde unit tests con Vitest hasta tests end-to-end con Playwright: todo lo que tu equipo necesita.',
    thumbnail: 'https://picsum.photos/seed/noticia10/600/400',
    link_web: 'https://vitest.dev/guides/frontend-testing',
    fecha_publicacion: '2026-04-10',
    fecha_scrapeo: '2026-04-10T19:00:00',
    tonos_sociales: ['Positivo', 'Neutro'],
    fuente_institucional: 'Vitest',
    tipo_fuente: 'Sitio web o portal',
    es_oficial: false,
    validado: true,
    analizado: true,
    actores_principales: ['Vitest Team'],
    adjuntos: ['https://archivos.ejemplo.com/testing/vitest-config-ejemplo.ts', 'https://archivos.ejemplo.com/testing/playwright-config-ejemplo.ts'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [
      { thumb: 'https://picsum.photos/seed/noticia10a/300/200', full: 'https://picsum.photos/seed/noticia10a/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia10b/300/200', full: 'https://picsum.photos/seed/noticia10b/600/400' }
    ],
    has_video: false,
    temas: [
      { titulo: 'Unit testing con Vitest y cobertura por componente para detectar regresiones', resumen: 'La configuracion optima de Vitest se detalla con cobertura por componente, mocks de dependencias, temporizadores y peticiones de red. Se explican los modos watch y coverage y la integracion con pre-commit, logrando una suite rapida que detecta regresiones antes de produccion.', tono_social: 'Positivo', fecha_narrativa: '2026-04-10' },
      { titulo: 'Integration tests centrados en roles accesibles y en el usuario real', resumen: 'Las pruebas de integracion con Testing Library se centran en el usuario real, interactuando con roles accesibles en lugar de detalles de implementacion. Son mas robustas ante refactorizaciones y cubren flujos como registro, autenticacion y carrito de compras.', tono_social: 'Neutro', fecha_narrativa: '2026-04-09' },
      { titulo: 'E2E con Playwright en paralelo en multiples navegadores y con captura de video', resumen: 'Playwright ejecuta pruebas end-to-end en paralelo en multiples navegadores, con captura de video y pantalla para diagnosticar fallas. La configuracion incluye redes interceptadas y sesion reutilizable, y el CI integra las pruebas en cada pull request.', tono_social: 'Positivo', fecha_narrativa: null }
    ]
  },
  {
    id: 'FUE-00011',
    nombre_fuente: 'La convergencia entre backend y frontend',
    resumen_ia: 'Meta-frameworks borran la linea entre servidor y cliente con server components y streaming.',
    thumbnail: 'https://picsum.photos/seed/noticia11/600/400',
    link_web: 'https://vercel.com/blog/frontend-backend-convergence',
    fecha_publicacion: '2024-03-20',
    fecha_scrapeo: '2026-03-20T15:15:00',
    tonos_sociales: ['Positivo', 'Negativo'],
    fuente_institucional: 'Vercel',
    tipo_fuente: 'Gacetilla o comunicado de prensa',
    es_oficial: true,
    validado: true,
    analizado: true,
    actores_principales: ['Vercel', 'Next.js Team', 'Juan Pérez'],
    notas_de_trabajo: 'Los costos de servidor son una preocupacion real. Revisar el analisis de costos antes de la proxima reunion de arquitectura y definir limites de uso.',
    adjuntos: ['https://archivos.ejemplo.com/vercel/demos/vercel-server-components-demo.zip', 'https://archivos.ejemplo.com/vercel/benchmarks/streaming-ssr-benchmarks.pdf', 'https://archivos.ejemplo.com/vercel/costos/analisis-costos-servidor.xlsx'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [
      { thumb: 'https://picsum.photos/seed/noticia11a/300/200', full: 'https://picsum.photos/seed/noticia11a/600/400' }
    ],
    has_video: false,
    temas: [
      { titulo: 'Server components que eliminan el JavaScript del renderizado inicial del cliente', resumen: 'Los componentes que se ejecutan solo en el servidor eliminan el envio de JavaScript al cliente para el renderizado inicial, reduciendo el bundle. La informacion sensible y las consultas a bases de datos quedan fuera del navegador, simplificando la seguridad.', tono_social: 'Positivo', fecha_narrativa: '2026-03-20' },
      { titulo: 'Streaming SSR y el renderizado progresivo de fragmentos sin bloquear la interaccion', resumen: 'El renderizado progresivo envia fragmentos de HTML al cliente a medida que estan listos. Mejora la percepcion de carga y muestra contenido interactivo temprano, mientras las secciones lentas aparecen progresivamente sin bloquear la interaccion.', tono_social: 'Positivo', fecha_narrativa: null, notas_de_trabajo: 'El streaming SSR puede mejorar el time to interactive. Probar en el dashboard de metricas donde tenemos problemas de carga lenta.' },
      { titulo: 'Costo de servidor y estrategias de cache para mitigar el consumo de recursos', resumen: 'La arquitectura de server components y streaming SSR implica mayor consumo de recursos en el servidor que una SPA tradicional. Cada renderizado demanda procesamiento y multiplica costos de hosting con trafico alto, por lo que conviene cache y descarga estatica.', tono_social: 'Negativo', fecha_narrativa: '2026-03-19', notas_de_trabajo: 'Hacer un estimado de costos antes de la proxima revision trimestral. Si supera el presupuesto actual, posponer la migracion.' }
    ]
  },
  {
    id: 'FUE-00012',
    nombre_fuente: 'Arquitectura de micro-frontends en produccion',
    resumen_ia: 'Como implementar micro-frontends con Module Federation, con resultados mixtos en equipos distribuidos.',
    thumbnail: 'https://picsum.photos/seed/noticia13/600/400',
    link_web: 'https://microfrontends.dev/case-study',
    fecha_publicacion: '',
    fecha_scrapeo: '2026-06-28T12:00:00',
    tonos_sociales: ['Positivo', 'Neutro'],
    fuente_institucional: 'MicroFrontends.dev',
    tipo_fuente: 'Sitio web o portal',
    es_oficial: false,
    validado: null,
    analizado: true,
    actores_principales: ['Module Federation Team', 'Sarah Connor'],
    adjuntos: ['https://archivos.ejemplo.com/microfrontends/caso-estudio-microfrontends.pdf'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [
      { thumb: 'https://picsum.photos/seed/noticia13a/300/200', full: 'https://picsum.photos/seed/noticia13a/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia13b/300/200', full: 'https://picsum.photos/seed/noticia13b/600/400' }
    ],
    has_video: false,
    temas: [
      { titulo: 'Module Federation y el compartir modulos entre aplicaciones en tiempo de ejecucion', resumen: 'Webpack 5 introdujo Module Federation, que permite compartir modulos entre aplicaciones independientes en tiempo de ejecucion sin instalar paquetes. Las aplicaciones exponen componentes que otros consumen de forma remota, facilitando plataformas modulares con equipos autonomas.', tono_social: 'Positivo', fecha_narrativa: null },
      { titulo: 'Orquestacion del shell principal con autenticacion, ruteo y estado compartido', resumen: 'El shell principal maneja ruteo, autenticacion, estado compartido y coordinacion de los micro-frontends remotos. Define los contratos de comunicacion, maneja la carga perezosa y centraliza branding y layout, lo que es critico para la consistencia.', tono_social: 'Neutro', fecha_narrativa: null },
      { titulo: 'Despliegue independiente de cada micro-frontend sin ventanas globales de coordinacion', resumen: 'Cada micro-frontend se despliega de forma independiente, sin coordinar con el resto de la plataforma ni esperar ventanas globales. Los cambios se verifican en aislamiento y el shell los consume de forma transparente, acelerando el ciclo de release.', tono_social: 'Positivo', fecha_narrativa: null }
    ]
  },
  {
    id: 'FUE-00013',
    nombre_fuente: 'Accesibilidad web: un compromiso permanente',
    resumen_ia: 'Nuevas herramientas y estandares facilitan la creacion de experiencias inclusivas para todos los usuarios.',
    thumbnail: 'https://picsum.photos/seed/noticia12/600/400',
    link_web: 'https://w3.org/wai/accessibility-2026',
    fecha_publicacion: '2025-02-05',
    fecha_scrapeo: '2026-02-05T10:00:00',
    tonos_sociales: ['Positivo', 'Negativo', 'Neutro'],
    fuente_institucional: 'W3C WAI',
    tipo_fuente: 'Decreto o norma',
    es_oficial: true,
    validado: true,
    analizado: true,
    actores_principales: ['WAI', 'Laura Jiménez', 'GovUK', 'Marta Ruiz', 'Carlos Mendoza', 'Sofía Torres', 'Diego Hernández', 'Valentina Paz', 'Javier Acosta', 'Lucía Campos'],
    adjuntos: ['https://archivos.ejemplo.com/accesibilidad/wcag-3-0-draft.pdf', 'https://archivos.ejemplo.com/accesibilidad/herramientas-accesibilidad-ci.pdf'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [
      { thumb: 'https://picsum.photos/seed/noticia12a/300/200', full: 'https://picsum.photos/seed/noticia12a/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia12b/300/200', full: 'https://picsum.photos/seed/noticia12b/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia12c/300/200', full: 'https://picsum.photos/seed/noticia12c/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia12d/300/200', full: 'https://picsum.photos/seed/noticia12d/600/400' },
      { thumb: 'https://picsum.photos/seed/noticia12e/300/200', full: 'https://picsum.photos/seed/noticia12e/600/400' }
    ],
    has_video: false,
    temas: [
      { titulo: 'WCAG 3.0 y los criterios de conformidad basados en resultados medibles', resumen: 'El estandar WCAG 3.0 introduce criterios de conformidad basados en resultados medibles en lugar de simples requisitos de implementacion. Contempla niveles de severidad y una puntuacion general, cubriendo navegacion por voz, movimiento reducido y contraste adaptativo.', tono_social: 'Positivo', fecha_narrativa: '2026-02-05' },
      { titulo: 'Herramientas de auditoria automatica integradas en el pipeline de CI', resumen: 'Los linters y auditores de accesibilidad se integran en los pipelines de CI y devuelven reportes con las violaciones detectadas en cada cambio. Verifican contraste, atributos de imagenes y roles interactivos, reduciendo costos de correccion.', tono_social: 'Positivo', fecha_narrativa: '2026-02-04' },
      { titulo: 'Legislacion y las multas por incumplimiento de las normativas de accesibilidad', resumen: 'Las multas por incumplimiento de las normativas de accesibilidad aumentaron un 200%. Las empresas sin acceso equitativo enfrentan sanciones economicas y danos reputacionales, impulsando la contratacion de consultores y la adopcion de herramientas de auditoria.', tono_social: 'Negativo', fecha_narrativa: '2026-02-03' },
      { titulo: 'Educacion y la demanda creciente de profesionales certificados en accesibilidad', resumen: 'La demanda de profesionales certificados en accesibilidad crece sostenidamente, impulsada por los nuevos marcos regulatorios. Universidades y plataformas amplian cursos y diplomaturas en diseno inclusivo, y estos perfiles logran mejor remuneracion.', tono_social: 'Neutro', fecha_narrativa: null }
    ]
  },
  {
    id: 'FUE-00014',
    nombre_fuente: 'Demostracion de animaciones CSS en YouTube',
    resumen_ia: 'Un video tutorial que muestra como crear animaciones complejas con solo CSS, sin necesidad de JavaScript.',
    thumbnail: 'https://picsum.photos/seed/youtube1/600/400',
    link_web: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    fecha_publicacion: '2025-06-28',
    fecha_scrapeo: '2026-06-28T10:00:00',
    tonos_sociales: ['Positivo'],
    fuente_institucional: 'YouTube',
    tipo_fuente: 'Video',
    es_oficial: false,
    validado: true,
    analizado: true,
    actores_principales: ['CSS Animations Channel'],
    adjuntos: [],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [],
    has_video: true,
    temas: [
      { titulo: 'Animaciones complejas con keyframes basicos, hover y transiciones en cascada', resumen: 'El tutorial explica paso a paso animaciones complejas solo con CSS, desde keyframes basicos hasta transiciones en cascada. Incluye ejemplos de hover, animaciones al hacer scroll y efectos de entrada, mostrando el potencial expresivo sin JavaScript.', tono_social: 'Positivo', fecha_narrativa: '2026-06-28' }
    ]
  },
  {
    id: 'FUE-00015',
    nombre_fuente: 'Nuevo framework CSS anunciado en Instagram',
    resumen_ia: 'Un desarrollador muestra en un reel de Instagram su nuevo framework CSS ligero para prototipado rapido.',
    thumbnail: 'https://picsum.photos/seed/instagram1/600/400',
    link_web: 'https://www.instagram.com/reel/DQ3zR6-DPGm/',
    fecha_publicacion: '2026-06-27',
    fecha_scrapeo: '2026-06-27T14:20:00',
    tonos_sociales: ['Positivo'],
    fuente_institucional: 'Instagram',
    tipo_fuente: 'Red Social',
    es_oficial: false,
    validado: true,
    analizado: true,
    actores_principales: ['dev_tips_css'],
    adjuntos: [],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [],
    has_video: true,
    temas: [
      { titulo: 'CSS framework ligero con utilidades de grid y flexbox para prototipado rapido', resumen: 'El framework CSS open-source acelera la maquetacion con sintaxis minimalista y archivo liviano. Incluye utilidades de grid y flexbox, componentes reutilizables y variables configurables, apuntando a desarrolladores que buscan resultados rapidos sin sistemas pesados.', tono_social: 'Positivo', fecha_narrativa: null }
    ]
  },
  {
    id: 'FUE-00016',
    nombre_fuente: 'Post viral sobre buenas practicas en React',
    resumen_ia: 'Un hilo en Twitter/X con consejos practicos para evitar re-renders innecesarios en aplicaciones React.',
    thumbnail: 'https://picsum.photos/seed/twitter1/600/400',
    link_web: 'https://x.com/elonmusk/status/1593459801966538755',
    fecha_publicacion: '2026-06-26',
    fecha_scrapeo: '2026-06-26T09:45:00',
    tonos_sociales: ['Positivo', 'Neutro'],
    fuente_institucional: 'Twitter',
    tipo_fuente: 'Red Social',
    es_oficial: true,
    validado: true,
    analizado: true,
    actores_principales: ['react_dev_tips'],
    adjuntos: ['https://archivos.ejemplo.com/twitter/hilo-twitter-react-tips.txt'],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [],
    has_video: false,
    temas: [
      { titulo: 'Performance y la optimizacion de renders con useMemo y useCallback', resumen: 'El hilo comparte consejos para optimizar React con el uso correcto de useMemo y useCallback para evitar renders innecesarios. Explica patrones de memorizacion, errores comunes y la importancia de medir con el profiler en lugar de optimizar a ciegas.', tono_social: 'Positivo', fecha_narrativa: '2026-06-26' },
      { titulo: 'React y las buenas practicas de ciclo de vida, estado y composicion', resumen: 'Un hilo con veinte consejos para escribir componentes mas eficientes, sobre ciclo de vida, estado y composicion. Abarca desde keys y renderizado condicional hasta custom hooks, con una justificacion breve y un ejemplo de codigo en cada recomendacion.', tono_social: 'Neutro', fecha_narrativa: null }
    ]
  },
  {
    id: 'FUE-00017',
    nombre_fuente: 'Post de Facebook sobre accesibilidad web',
    resumen_ia: 'Un desarrollador comparte en Facebook su experiencia implementando WCAG 3.0 en proyectos reales con consejos practicos.',
    thumbnail: 'https://picsum.photos/seed/facebook1/600/400',
    link_web: null,
    fecha_publicacion: '2026-06-24',
    fecha_scrapeo: '2026-06-24T11:30:00',
    tonos_sociales: ['Positivo'],
    fuente_institucional: 'Facebook',
    tipo_fuente: 'Red Social',
    es_oficial: false,
    validado: true,
    analizado: true,
    actores_principales: ['Comunidad Web Dev'],
    adjuntos: [],
    screenshot: 'https://picsum.photos/seed/captura/400/800',
    imagenes: [],
    has_video: false,
    temas: [
      { titulo: 'WCAG 3.0 aplicado en proyectos reales de produccion con consejos practicos', resumen: 'El desarrollador comparte su experiencia implementando los nuevos estandares de accesibilidad en proyectos reales. Destaca involucrar al diseno desde el inicio, combinar auditoria automatica con evaluacion manual y planificar el presupuesto de correcciones.', tono_social: 'Positivo', fecha_narrativa: '2026-06-24' }
    ]
  },
  {
    id: 'FUE-00018',
    analizado: false,
    nombre_fuente: '',
    resumen_ia: '',
    thumbnail: null,
    link_web: 'https://ejemplo.com/fuente/sin-analizar/FUE-00018',
    fecha_publicacion: '',
    fecha_scrapeo: '',
    tonos_sociales: [],
    fuente_institucional: '',
    tipo_fuente: '',
    es_oficial: false,
    validado: null,
    actores_principales: [],
    adjuntos: [],
    screenshot: null,
    imagenes: [],
    has_video: false,
    temas: []
  },
  {
    id: 'FUE-00019',
    analizado: false,
    nombre_fuente: '',
    resumen_ia: '',
    thumbnail: null,
    link_web: 'https://ejemplo.com/fuente/sin-analizar/FUE-00019',
    fecha_publicacion: '',
    fecha_scrapeo: '',
    tonos_sociales: [],
    fuente_institucional: '',
    tipo_fuente: '',
    es_oficial: false,
    validado: null,
    actores_principales: [],
    adjuntos: [],
    screenshot: null,
    imagenes: [],
    has_video: false,
    temas: []
  }
] };
